import { getShopIdFromRequest } from '@/app/constants/shop';
import { NextResponse } from 'next/server';
import { getPosDb, type DbConnection } from '../db';
import { getSoftwareVersion, getSoftwareName } from '@/app/utils/version';
import { NF525_CERTIFICATE_NUMBER } from '@/app/utils/constants';

export const dynamic = 'force-dynamic';

export async function GET(request: Request) {
    const shopId = getShopIdFromRequest(request);
    let connection: DbConnection | undefined;
    try {
        connection = await getPosDb(shopId);
        const isPg = connection.isPostgreSQL;
        const prefix = isPg ? 'dc_pos.' : '';

        // Fetch shop parameters for company info
        const [paramRows] = await connection.execute(
            `SELECT param_key, param_value FROM ${prefix}parameters WHERE param_key IN ('shopName', 'shopSiret', 'shopVatNumber', 'shopAddress', 'shopZipCode', 'shopCity')`
        );
        const params = new Map<string, string>();
        for (const row of paramRows as { param_key: string; param_value: string }[]) {
            params.set(row.param_key, row.param_value);
        }

        // Count transactions, closures, audit events
        const countQuery = (table: string) =>
            isPg ? `SELECT COUNT(*)::int AS c FROM ${prefix}${table}` : `SELECT COUNT(*) AS c FROM ${prefix}${table}`;
        const [txCount] = await connection.execute(countQuery('transactions'));
        const [dailyCount] = await connection.execute(countQuery('daily_closures'));
        const [monthlyCount] = await connection.execute(countQuery('monthly_closures'));
        const [annualCount] = await connection.execute(countQuery('annual_closures'));
        const [auditCount] = await connection.execute(countQuery('audit_events'));

        // Get first and last transaction dates
        const [dateRange] = await connection.execute(
            isPg
                ? `SELECT MIN(created_at)::text AS first_date, MAX(created_at)::text AS last_date FROM ${prefix}transactions`
                : `SELECT MIN(created_at) AS first_date, MAX(created_at) AS last_date FROM ${prefix}transactions`
        );
        const dates = (dateRange as { first_date: string | null; last_date: string | null }[])[0];

        // Get perpetual totals
        const [perpRows] = await connection.execute(`SELECT * FROM ${prefix}perpetual_totals WHERE id = 1`);
        const perpetual = (perpRows as unknown[])[0] ?? null;

        const certificate = {
            certificate_type: 'NF525 Self-Certification',
            certificate_number: NF525_CERTIFICATE_NUMBER,
            generated_at: new Date().toISOString(),
            software: {
                name: getSoftwareName(),
                version: getSoftwareVersion(),
            },
            company: {
                name: params.get('shopName') || '',
                siret: params.get('shopSiret') || '',
                vat_number: params.get('shopVatNumber') || '',
                address: params.get('shopAddress') || '',
                zip_code: params.get('shopZipCode') || '',
                city: params.get('shopCity') || '',
            },
            data_summary: {
                transaction_count: (txCount as { c: number }[])[0]?.c ?? 0,
                daily_closure_count: (dailyCount as { c: number }[])[0]?.c ?? 0,
                monthly_closure_count: (monthlyCount as { c: number }[])[0]?.c ?? 0,
                annual_closure_count: (annualCount as { c: number }[])[0]?.c ?? 0,
                audit_event_count: (auditCount as { c: number }[])[0]?.c ?? 0,
                first_transaction_date: dates?.first_date ?? null,
                last_transaction_date: dates?.last_date ?? null,
            },
            perpetual_totals: perpetual,
            compliance_features: {
                inalterability: 'SHA-256 chained hashing on all transactions',
                integrity_verification: 'Daily/monthly/annual closures with chained hashes',
                audit_trail: 'All sensitive operations logged with chained hashes in audit_events',
                data_export: 'Fiscal archive export available via /api/sql/fiscalArchive',
                perpetual_totals: 'Running accumulator with last closure hash anchor',
            },
            note: 'This certificate is auto-generated by the software. Official NF525 certification must be issued by an accredited body (e.g. LNE).',
        };

        const filename = `nf525_certificate_${new Date().toISOString().substring(0, 10)}.json`;
        return new NextResponse(JSON.stringify(certificate, null, 2), {
            status: 200,
            headers: {
                'Content-Type': 'application/json',
                'Content-Disposition': `attachment; filename="${filename}"`,
            },
        });
    } catch (error) {
        console.error('Error generating certificate:', error);
        return NextResponse.json({ error: 'Failed to generate certificate' }, { status: 500 });
    } finally {
        await connection?.end();
    }
}
