/**
 * Fetch existing data for a shop from the running API and generate
 * an idempotent import SQL script (similar to import-gds-data.sql).
 *
 * Usage:
 *   bun scripts/export-shop-data.ts <shopId> [outputFile]
 *
 * Example:
 *   bun scripts/export-shop-data.ts annette scripts/import-annette-data.sql
 */

import { SHOP_IDS } from '../src/app/constants/shops';

const SHOP_ID = process.argv[2];
const OUTPUT_FILE = process.argv[3] || `scripts/import-${SHOP_ID}-data.sql`;

if (!SHOP_ID || !SHOP_IDS.includes(SHOP_ID as (typeof SHOP_IDS)[number])) {
    console.error(`Usage: bun scripts/export-shop-data.ts <shopId> [outputFile]`);
    console.error(`Valid shop IDs: ${SHOP_IDS.join(', ')}`);
    process.exit(1);
}

// We hit the local dev server
const BASE_URL = process.env.BASE_URL || 'http://localhost:3000';

interface ParameterRow {
    id: number;
    param_key: string;
    param_value: string;
    updated_at: string;
}

interface UserRow {
    id: number;
    name: string;
    role: string;
    reference: string | null;
    created_at: string;
}

interface PaymentMethodRow {
    id: number;
    label: string;
    address: string;
    currency: string;
    available: boolean;
    created_at: string;
}

interface PrinterRow {
    id: number;
    name: string;
    ip_address: string;
}

interface DeviceRow {
    id: number;
    label: string;
    public_key: string;
    user_id: number;
    connected: boolean;
    last_seen: string;
    created_at: string;
}

interface CompanyRow {
    name: string;
    employer_share: number;
}

interface CustomerRow {
    id: number;
    name: string;
    email: string | null;
    phone: string | null;
    address: string | null;
    balance: number;
    created_at: string;
}

interface ThemeAdminRow {
    id: number;
    selected: boolean;
    name: string;
    text_light: string;
    text_dark: string;
    gradient_start_light: string;
    gradient_start_dark: string;
    gradient_end_light: string;
    gradient_end_dark: string;
    popup_light: string;
    popup_dark: string;
    activated_light: string;
    activated_dark: string;
    secondary_light: string;
    secondary_dark: string;
    secondary_activated_light: string;
    secondary_activated_dark: string;
}

interface CategoryRow {
    id: number;
    name: string;
    sort_order: number;
    company_id: string | null;
}

interface ProductRow {
    id: number;
    sort_order: number;
    name: string;
    price: number;
    reference: string;
    category_id: number;
    stock: number | null;
    photo: string | null;
    description: string | null;
    vat_rate: number;
    color: string | null;
    employer_share: number | null;
}

function sqlEscape(value: string | null): string {
    if (value === null || value === undefined) return 'NULL';
    return `'${value.replace(/'/g, "''")}'`;
}

async function fetchJson(path: string): Promise<unknown> {
    const res = await fetch(`${BASE_URL}${path}`);
    if (!res.ok) {
        throw new Error(`Failed to fetch ${path}: ${res.status}`);
    }
    return res.json();
}

async function main() {
    console.log(`Fetching data for shop: ${SHOP_ID} from ${BASE_URL}`);

    // Fetch all data in parallel
    const [parameters, users, paymentMethods, printers, devices, companies, customers, categories, products] =
        await Promise.all([
            fetchJson(`/api/sql/getParameters?shopId=${SHOP_ID}`) as Promise<{ parameters: ParameterRow[] }>,
            fetchJson(`/api/sql/users?shopId=${SHOP_ID}`) as Promise<{ users: UserRow[] }>,
            fetchJson(`/api/sql/getPaymentMethods?shopId=${SHOP_ID}`) as Promise<{
                paymentMethods: PaymentMethodRow[];
            }>,
            fetchJson(`/api/sql/getPrinters?shopId=${SHOP_ID}`) as Promise<{ printers: PrinterRow[] }>,
            fetchJson(`/api/sql/getDevices?shopId=${SHOP_ID}`) as Promise<{ devices: DeviceRow[] }>,
            fetchJson(`/api/sql/getCompanies?shopId=${SHOP_ID}`) as Promise<{ companies: CompanyRow[] }>,
            fetchJson(`/api/sql/getCustomers?shopId=${SHOP_ID}`) as Promise<{ customers: CustomerRow[] }>,
            fetchJson(`/api/sql/getCategories?shopId=${SHOP_ID}`) as Promise<{ categories: CategoryRow[] }>,
            fetchJson(`/api/sql/getProducts?shopId=${SHOP_ID}`) as Promise<{ products: ProductRow[] }>,
        ]);

    let sql = `-- ============================================================\n`;
    sql += `-- ${SHOP_ID} Data Import Script\n`;
    sql += `-- Auto-generated by scripts/export-shop-data.ts\n`;
    sql += `-- Generated: ${new Date().toISOString()}\n`;
    sql += `--\n`;
    sql += `-- This script is IDEMPOTENT: it uses ON CONFLICT DO NOTHING\n`;
    sql += `-- and can be safely rerun without creating duplicates.\n`;
    sql += `-- ============================================================\n\n`;

    sql += `BEGIN;\n\n`;

    // Parameters
    sql += `-- ============================================================\n`;
    sql += `-- Parameters\n`;
    sql += `-- ============================================================\n`;
    for (const p of parameters.parameters) {
        sql += `INSERT INTO dc_pos.parameters (id, param_key, param_value, updated_at) VALUES (${p.id}, ${sqlEscape(p.param_key)}, ${sqlEscape(p.param_value)}, ${sqlEscape(p.updated_at)}) ON CONFLICT (id) DO NOTHING;\n`;
    }
    sql += `\n`;

    // Users
    if (users.users.length > 0) {
        sql += `-- ============================================================\n`;
        sql += `-- Users\n`;
        sql += `-- ============================================================\n`;
        for (const u of users.users) {
            sql += `INSERT INTO dc_pos.users (id, name, role, reference, created_at) VALUES (${u.id}, ${sqlEscape(u.name)}, ${sqlEscape(u.role)}, ${sqlEscape(u.reference)}, ${sqlEscape(u.created_at)}) ON CONFLICT (id) DO NOTHING;\n`;
        }
        sql += `\n`;
    }

    // Payment methods
    if (paymentMethods.paymentMethods.length > 0) {
        sql += `-- ============================================================\n`;
        sql += `-- Payment methods\n`;
        sql += `-- ============================================================\n`;
        for (const pm of paymentMethods.paymentMethods) {
            sql += `INSERT INTO dc_pos.payment_methods (id, label, address, currency, available, created_at) VALUES (${pm.id}, ${sqlEscape(pm.label)}, ${sqlEscape(pm.address)}, ${sqlEscape(pm.currency)}, ${pm.available}, ${sqlEscape(pm.created_at)}) ON CONFLICT (id) DO NOTHING;\n`;
        }
        sql += `\n`;
    }

    // Printers
    if (printers.printers.length > 0) {
        sql += `-- ============================================================\n`;
        sql += `-- Printers\n`;
        sql += `-- ============================================================\n`;
        for (const p of printers.printers) {
            sql += `INSERT INTO dc_pos.printers (id, name, ip_address) VALUES (${p.id}, ${sqlEscape(p.name)}, ${sqlEscape(p.ip_address)}) ON CONFLICT (id) DO NOTHING;\n`;
        }
        sql += `\n`;
    }

    // Devices
    if (devices.devices.length > 0) {
        sql += `-- ============================================================\n`;
        sql += `-- Devices\n`;
        sql += `-- ============================================================\n`;
        for (const d of devices.devices) {
            sql += `INSERT INTO dc_pos.devices (id, label, public_key, user_id, connected, last_seen, created_at) VALUES (${d.id}, ${sqlEscape(d.label)}, ${sqlEscape(d.public_key)}, ${d.user_id}, ${d.connected ? 't' : 'f'}, ${sqlEscape(d.last_seen)}, ${sqlEscape(d.created_at)}) ON CONFLICT (id) DO NOTHING;\n`;
        }
        sql += `\n`;
    }

    // Companies
    if (companies.companies.length > 0) {
        sql += `-- ============================================================\n`;
        sql += `-- Companies\n`;
        sql += `-- ============================================================\n`;
        for (const c of companies.companies) {
            sql += `INSERT INTO dc_pos.companies (name, employer_share) VALUES (${sqlEscape(c.name)}, ${c.employer_share}) ON CONFLICT (name) DO NOTHING;\n`;
        }
        sql += `\n`;
    }

    // Customers
    if (customers.customers.length > 0) {
        sql += `-- ============================================================\n`;
        sql += `-- Customers\n`;
        sql += `-- ============================================================\n`;
        for (const c of customers.customers) {
            sql += `INSERT INTO dc_pos.customers (id, name, email, phone, address, balance, created_at) VALUES (${c.id}, ${sqlEscape(c.name)}, ${sqlEscape(c.email)}, ${sqlEscape(c.phone)}, ${sqlEscape(c.address)}, ${c.balance}, ${sqlEscape(c.created_at)}) ON CONFLICT (id) DO NOTHING;\n`;
        }
        sql += `\n`;
    }

    // Themes
    sql += `-- ============================================================\n`;
    sql += `-- Themes\n`;
    sql += `-- ============================================================\n`;
    // Fetch raw theme rows
    try {
        const themeRes = await fetch(`${BASE_URL}/api/sql/getColors?shopId=${SHOP_ID}&all=1&raw=1`);
        if (themeRes.ok) {
            const themeData = (await themeRes.json()) as { rows: ThemeAdminRow[] };
            for (const t of themeData.rows) {
                sql += `INSERT INTO dc.theme_admin (id, selected, name, text_light, text_dark, gradient_start_light, gradient_start_dark, gradient_end_light, gradient_end_dark, popup_light, popup_dark, activated_light, activated_dark, secondary_light, secondary_dark, secondary_activated_light, secondary_activated_dark) VALUES (${t.id}, ${t.selected ? 't' : 'f'}, ${sqlEscape(t.name)}, ${sqlEscape(t.text_light)}, ${sqlEscape(t.text_dark)}, ${sqlEscape(t.gradient_start_light)}, ${sqlEscape(t.gradient_start_dark)}, ${sqlEscape(t.gradient_end_light)}, ${sqlEscape(t.gradient_end_dark)}, ${sqlEscape(t.popup_light)}, ${sqlEscape(t.popup_dark)}, ${sqlEscape(t.activated_light)}, ${sqlEscape(t.activated_dark)}, ${sqlEscape(t.secondary_light)}, ${sqlEscape(t.secondary_dark)}, ${sqlEscape(t.secondary_activated_light)}, ${sqlEscape(t.secondary_activated_dark)}) ON CONFLICT (id) DO NOTHING;\n`;
            }
        }
    } catch {
        sql += `-- Themes: could not fetch raw rows\n`;
    }
    sql += `\n`;

    // Categories
    if (categories.categories.length > 0) {
        sql += `-- ============================================================\n`;
        sql += `-- Categories\n`;
        sql += `-- ============================================================\n`;
        for (const c of categories.categories) {
            sql += `INSERT INTO dc.categories (id, name, sort_order, company_id) VALUES (${c.id}, ${sqlEscape(c.name)}, ${c.sort_order}, ${sqlEscape(c.company_id)}) ON CONFLICT (id) DO NOTHING;\n`;
        }
        sql += `\n`;
    }

    // Products
    if (products.products.length > 0) {
        sql += `-- ============================================================\n`;
        sql += `-- Products\n`;
        sql += `-- ============================================================\n`;
        for (const p of products.products) {
            sql += `INSERT INTO dc.products (sort_order, name, price, reference, category_id, vat_rate${p.stock !== null ? ', stock' : ''}${p.photo ? ', photo' : ''}${p.description ? ', description' : ''}${p.color ? ', color' : ''}${p.employer_share !== null ? ', employer_share' : ''}) VALUES (${p.sort_order}, ${sqlEscape(p.name)}, ${p.price}, ${sqlEscape(p.reference)}, ${p.category_id}, ${p.vat_rate}${p.stock !== null ? `, ${p.stock}` : ''}${p.photo ? `, ${sqlEscape(p.photo)}` : ''}${p.description ? `, ${sqlEscape(p.description)}` : ''}${p.color ? `, ${sqlEscape(p.color)}` : ''}${p.employer_share !== null ? `, ${p.employer_share}` : ''}) ON CONFLICT (reference) DO NOTHING;\n`;
        }
        sql += `\n`;
    }

    sql += `COMMIT;\n`;

    // @ts-expect-error — Bun.write is available at runtime in Bun
    await Bun.write(OUTPUT_FILE, sql);
    console.log(`✓ Written ${sql.length} bytes to ${OUTPUT_FILE}`);
    console.log(`  Parameters: ${parameters.parameters.length}`);
    console.log(`  Users: ${users.users.length}`);
    console.log(`  Payment methods: ${paymentMethods.paymentMethods.length}`);
    console.log(`  Printers: ${printers.printers.length}`);
    console.log(`  Devices: ${devices.devices.length}`);
    console.log(`  Companies: ${companies.companies.length}`);
    console.log(`  Customers: ${customers.customers.length}`);
    console.log(`  Categories: ${categories.categories.length}`);
    console.log(`  Products: ${products.products.length}`);
}

main().catch((err) => {
    console.error('Error:', err);
    process.exit(1);
});
