#!/bin/sh
if git diff --cached --name-only | grep -E '\.(ts(x)?|js(x)?)$'; 
then 
    echo "Running tests..."
    bun test || exit 1
    echo "Running build..."
    bun run build || exit 1
else 
    echo "Running lint..."
    bun lint
fi

echo "Pre-commit checks passed!"
